apiVersion: v1
kind: Service
metadata:
  name: bigtable-deployment-service
  namespace: test-ws
spec:
  selector:
    app: bigtable-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4567
      targetPort: 4567  # Port your app is listening on